### PR TITLE
Consistency

### PR DESCRIPTION
**Pull request by Rahban1**
greeting, I just now added the file in app/messages 
hope you are having a good day :)

### CODE REVIEW

**Review by SavvasStephanides — CHANGES_REQUESTED** [review]
Thank you @Rahban1! Good work!

A couple of things:

* Please remove the `.txt` extension from the file so your file is just named `consistency`.
* Remove the other `consistency` file from the route directory.

Thank you!

**Comment by Rahban1** [comment]
i deleted the earlier consistency file and also removed the .txt extension 
thank you for your patience :)

**Review by SavvasStephanides — CHANGES_REQUESTED** [review]
No problem, @Rahban1! Thank you for responding! One last thing:

Start your file with an upper-case `By: ` (instead of `by: `) and I'll be happy to approve!

**Comment by Rahban1** [comment]
no problem , done with the changes you ask for :)

**Review by SavvasStephanides — APPROVED** [review]
Thank you so much @Rahban1! I have approved your pull request! Your message should be visible here once it gets deployed! 🎉

https://just-say-something.vercel.app/message/consistency

Congratulations on your first pull request! 🔥

**Comment by Rahban1** [comment]
Thank you so much @SavvasStephanides . Thank you for being patient and helpful :)

**Pull request merged**
